SELECT PROJECTS.DOMAIN_NAME as "DOMAIN NAME", PROJECTS.PROJECT_NAME as "PROJECT NAME", MAX(SESSIONS_HISTORY.START_TIME) as "LAST LOGIN"

FROM qcsiteadmin_db.td.PROJECTS left outer join qcsiteadmin_db.td.SESSIONS_HISTORY SESSIONS_HISTORY



On (PROJECTS.PROJECT_NAME=SESSIONS_HISTORY.PROJECT_NAME) AND (PROJECTS.DOMAIN_NAME=SESSIONS_HISTORY.DOMAIN_NAME)



GROUP by PROJECTS.DOMAIN_NAME, PROJECTS.PROJECT_NAME
